### PR TITLE
What do you think?

### PR DESCRIPTION
**Pull request by thealamu**
I may need help with the postal code and country section and the overall layout.
screenshot

### CODE REVIEW

**Comment by Weirdricc** [comment]
Looking at the code, it should be fine

**Comment by thealamu** [comment]
Need help with the country and postal code sections

**Comment by Weirdricc** [comment]
Or i should have dropped the finish notice here? I really don't know how to navigate this interface much 😅

**Comment by thealamu** [comment]
It only gets easier. I'm checking it out now.

**Pull request merged**
